fixed label check

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -15,12 +15,20 @@ env:
 jobs:
   check:
     runs-on: ubuntu-latest
+    if: |
+      github.event.pull_request.labels.*.name != 'devops' ||
+      github.event.pull_request.labels.*.name != 'infrastructure' ||
+      github.event.pull_request.labels.*.name != 'frontend' ||
+      github.event.pull_request.labels.*.name != 'backend'
     steps:
-      - name: label
-        run: contains(fromJSON('["frontend", "backend", "devops", "infrastructure"]'), github.event.issue.labels.*.name)
+      - name: message
+        run: |
+          echo "Label required '(frontend, backend, devops, infrastructure)' not found."
+          exit 1
 
   build:
     runs-on: ubuntu-latest
+    needs: check
     steps:
       - name: Checkout Git
         uses: actions/checkout@v4
@@ -33,6 +41,7 @@ jobs:
 
   test:
     runs-on: ubuntu-latest
+    needs: check
     steps:
       - name: Checkout Git
         uses: actions/checkout@v4
@@ -45,6 +54,7 @@ jobs:
 
   lint:
     runs-on: ubuntu-latest
+    needs: check
     steps:
       - name: Checkout Git
         uses: actions/checkout@v4
@@ -57,12 +67,10 @@ jobs:
 
   security:
     runs-on: ubuntu-latest
+    needs: check
     steps:
       - name: Check out code
         uses: actions/checkout@v4
-
-      - name: Configure Worflow
-        uses: ./.github/actions/configure
 
       - name: Run Snyk to check for vulnerabilities
         uses: snyk/actions/node@master
